In [1]:
import sys
sys.path.append("/Users/avelezxerenity/Documents/GitHub/pysdk")
import os
from inflation_query.Inflation_query import implied_inflation_calc
from src.xerenity.xty import Xerenity
from utilities.date_functions import add_months,ql_to_datetime
from utilities.rate_conversion_functions import nom_to_effective
from swap_functions.ibr_quantlib_details import ibr_quantlib_det,ibr_overnight_index,ibr_swap_cupon_helper,depo_helpers_ibr
from swap_functions.ibr_swap_ql_functions import ibr_swaps_quotes,crear_objeto_curva_ibr,fwd_rates_generation
from swap_functions.quotes_query import ibr_mean_query
from swap_functions.main import full_ibr_curve_creation
import pandas as pd
import QuantLib as ql
import plotly.graph_objects as go
from datetime import datetime,date
import matplotlib.pyplot as plt
xty = Xerenity(
    username=os.getenv('XTY_USER'),
    password=os.getenv('XTY_PWD'),
)



#calc_date = ql.Date(2, 11, 2023)
#ql.Settings.instance().evaluationDate = calc_date

svelezsaffon@gmail.com

2023-12-19 13:12:10,309:INFO - HTTP Request: POST https://tvpehjbqxpiswkqszwwv.supabase.co/auth/v1/token?grant_type=password "HTTP/1.1 200 OK"

<QuantLib.QuantLib.SwapRateHelper; proxy of <Swig Object of type 'ext::shared_ptr< SwapRateHelper > *' at 0x1476e99b0> >

2023-12-19 13:12:10,844:INFO - HTTP Request: POST https://tvpehjbqxpiswkqszwwv.supabase.co/auth/v1/token?grant_type=password "HTTP/1.1 200 OK"
2023-12-19 13:12:11,354:INFO - HTTP Request: POST https://tvpehjbqxpiswkqszwwv.supabase.co/auth/v1/token?grant_type=password "HTTP/1.1 200 OK"
2023-12-19 13:12:11,685:INFO - HTTP Request: GET https://tvpehjbqxpiswkqszwwv.supabase.co/rest/v1/banrep_serie_value?select=%2A&id_serie=eq.19&order=fecha.desc&limit=1 "HTTP/1.1 200 OK"
2023-12-19 13:12:12,058:INFO - HTTP Request: GET https://tvpehjbqxpiswkqszwwv.supabase.co/rest/v1/ibr_swaps_cluster?select=%2A "HTTP/1.1 200 OK"
/Users/avelezxerenity/Documents/GitHub/pysdk/src/xerenity/xty.py:134: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[column] = pd.to_datetime(df[column])
/Users/avelezxerenity/Documents/GitHub/pysdk/src/xerenity/xty.py:134: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[column] = pd.to_datetime(df[column])
/Users/avelezxerenity/Documents/GitHub/pysdk/src/xerenity/xty.py:134: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[column] = pd.to_datetime(df[column])
2023-12-19 13:12:12,702:INFO - HTTP Request: GET https://tvpehjbqxpiswkqszwwv.supabase.co/rest/v1/ibr_swaps_cluster?select=%2A "HTTP/1.1 200 OK"

{'index': 0, 'tenor': 3, 'rate': 0.12065000000000001, 'tenor_unit': 'm'}
{'index': 1, 'tenor': 6, 'rate': 0.11865, 'tenor_unit': 'm'}
{'index': 2, 'tenor': 9, 'rate': 0.11507500000000001, 'tenor_unit': 'm'}
{'index': 3, 'tenor': 12, 'rate': 0.1103, 'tenor_unit': 'm'}
{'index': 4, 'tenor': 24, 'rate': 0.08972098428571429, 'tenor_unit': 'm'}
{'index': 5, 'tenor': 36, 'rate': 0.08221666666666666, 'tenor_unit': 'm'}
{'index': 6, 'tenor': 48, 'rate': 0.0791, 'tenor_unit': 'm'}
{'index': 7, 'tenor': 60, 'rate': 0.07702333333333333, 'tenor_unit': 'm'}
{'index': 8, 'tenor': 96, 'rate': 0.07765, 'tenor_unit': 'm'}
{'index': 9, 'tenor': 108, 'rate': 0.07765, 'tenor_unit': 'm'}
{'index': 10, 'tenor': 120, 'rate': 0.08799241375, 'tenor_unit': 'm'}
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
fwd curve tenor to calculate not in curve quotes
[{'fecha': '2025-01-24 00:00:00', 'rate': 0.07878766785890834}, {'fecha': '2025-02-24 00:00:00', 'rate': 0.07655551503711688}, {'fecha': '2025-03-24 00:00:00', 'rate': 0.07460407441441719}, {'fecha': '2025-04-24 00:00:00', 'rate': 0.07279237779182712}, {'fecha': '2025-05-24 00:00:00', 'rate': 0.07120595989622913}, {'fecha': '2025-06-24 00:00:00', 'rate': 0.06982423134172921}, {'fecha': '2025-07-24 00:00:00', 'rate': 0.0687153082095846}, {'fecha': '2025-08-24 00:00:00', 'rate': 0.06781047892669334}, {'fecha': '2025-09-24 00:00:00', 'rate': 0.0671625016198183}, {'fecha': '2025-10-24 00:00:00', 'rate': 0.06675206921526122}, {'fecha': '2025-11-24 00:00:00', 'rate': 0.06651727017228604}, {'fecha': '2025-12-24 00:00:00', 'rate': 0.06640675821368691}, {'fecha': '2026-01-24 00:00:00', 'rate': 0.06635614618861663}, {'fecha': '2026-02-24 00:00:00', 'rate': 0.0663650947177068}, {'fecha': '2026-03-24 00:00:00', 'rate': 0.0664328182538012}, {'fecha': '2026-04-24 00:00:00', 'rate': 0.06656117044591392}, {'fecha': '2026-05-24 00:00:00', 'rate': 0.06675326684545912}, {'fecha': '2026-06-24 00:00:00', 'rate': 0.06701370709023013}, {'fecha': '2026-07-24 00:00:00', 'rate': 0.06733025228448919}, {'fecha': '2026-08-24 00:00:00', 'rate': 0.06772553635218181}, {'fecha': '2026-09-24 00:00:00', 'rate': 0.06818306359120707}, {'fecha': '2026-10-24 00:00:00', 'rate': 0.06869917255185798}, {'fecha': '2026-11-24 00:00:00', 'rate': 0.0692324665671391}, {'fecha': '2026-12-24 00:00:00', 'rate': 0.06968986888310424}, {'fecha': '2027-01-24 00:00:00', 'rate': 0.07008603232584987}, {'fecha': '2027-02-24 00:00:00', 'rate': 0.07037548932561677}, {'fecha': '2027-03-24 00:00:00', 'rate': 0.07055437149932153}, {'fecha': '2027-04-24 00:00:00', 'rate': 0.07063932291372677}, {'fecha': '2027-05-24 00:00:00', 'rate': 0.0706148671120046}, {'fecha': '2027-06-24 00:00:00', 'rate': 0.07047803856626955}, {'fecha': '2027-07-24 00:00:00', 'rate': 0.0702348416496581}, {'fecha': '2027-08-24 00:00:00', 'rate': 0.06986654410407045}, {'fecha': '2027-09-24 00:00:00', 'rate': 0.0693867060962512}, {'fecha': '2027-10-24 00:00:00', 'rate': 0.06881000304054075}, {'fecha': '2027-11-24 00:00:00', 'rate': 0.06821822672118838}, {'fecha': '2027-12-24 00:00:00', 'rate': 0.0677429362562958}, {'fecha': '2028-01-24 00:00:00', 'rate': 0.06741798019677003}, {'fecha': '2028-02-24 00:00:00', 'rate': 0.06728443978638587}, {'fecha': '2028-03-24 00:00:00', 'rate': 0.06734341662886068}, {'fecha': '2028-04-24 00:00:00', 'rate': 0.0675915918853276}, {'fecha': '2028-05-24 00:00:00', 'rate': 0.06804208172015902}, {'fecha': '2028-06-24 00:00:00', 'rate': 0.06870713424492969}, {'fecha': '2028-07-24 00:00:00', 'rate': 0.06955610052423533}, {'fecha': '2028-08-24 00:00:00', 'rate': 0.07065101590184764}, {'fecha': '2028-09-24 00:00:00', 'rate': 0.07194803630749846}, {'fecha': '2028-10-24 00:00:00', 'rate': 0.07344806664125736}, {'fecha': '2028-11-24 00:00:00', 'rate': 0.07508233989532664}, {'fecha': '2028-12-24 00:00:00', 'rate': 0.0766184551079383}, {'fecha': '2029-01-24 00:00:00', 'rate': 0.07818349028484106}, {'fecha': '2029-02-24 00:00:00', 'rate': 0.07963375141766038}, {'fecha': '2029-03-24 00:00:00', 'rate': 0.08094575512493374}, {'fecha': '2029-04-24 00:00:00', 'rate': 0.082212116174186}, {'fecha': '2029-05-24 00:00:00', 'rate': 0.08337916744325868}, {'fecha': '2029-06-24 00:00:00', 'rate': 0.08446298185187096}, {'fecha': '2029-07-24 00:00:00', 'rate': 0.08540970646417056}, {'fecha': '2029-08-24 00:00:00', 'rate': 0.08627913929590347}, {'fecha': '2029-09-24 00:00:00', 'rate': 0.08702412915178748}, {'fecha': '2029-10-24 00:00:00', 'rate': 0.08765331200880633}, {'fecha': '2029-11-24 00:00:00', 'rate': 0.08817334739885929}, {'fecha': '2029-12-24 00:00:00', 'rate': 0.08854860096059847}, {'fecha': '2030-01-24 00:00:00', 'rate': 0.08882285184933303}, {'fecha': '2030-02-24 00:00:00', 'rate': 0.08896415578047212}, {'fecha': '2030-03-24 00:00:00', 'rate': 0.08897063126950311}, {'fecha': '2030-04-24 00:00:00', 'rate': 0.08884790443152912}, {'fecha': '2030-05-24 00:00:00', 'rate': 0.08858294106464282}, {'fecha': '2030-06-24 00:00:00', 'rate': 0.08816743471957}, {'fecha': '2030-07-24 00:00:00', 'rate': 0.08762012449080214}, {'fecha': '2030-08-24 00:00:00', 'rate': 0.086900674929002}, {'fecha': '2030-09-24 00:00:00', 'rate': 0.08603776369783112}, {'fecha': '2030-10-24 00:00:00', 'rate': 0.08501352936120665}, {'fecha': '2030-11-24 00:00:00', 'rate': 0.0838076428618415}, {'fecha': '2030-12-24 00:00:00', 'rate': 0.08252760808298709}, {'fecha': '2031-01-24 00:00:00', 'rate': 0.0809878969535589}, {'fecha': '2031-02-24 00:00:00', 'rate': 0.07930164817617857}, {'fecha': '2031-03-24 00:00:00', 'rate': 0.07749942041985158}, {'fecha': '2031-04-24 00:00:00', 'rate': 0.0754686155673363}, {'fecha': '2031-05-24 00:00:00', 'rate': 0.07325649216774788}, {'fecha': '2031-06-24 00:00:00', 'rate': 0.07082517235763874}, {'fecha': '2031-07-24 00:00:00', 'rate': 0.06829397669605264}, {'fecha': '2031-08-24 00:00:00', 'rate': 0.06549329588556252}, {'fecha': '2031-09-24 00:00:00', 'rate': 0.06255538125231963}, {'fecha': '2031-10-24 00:00:00', 'rate': 0.05956166357281534}, {'fecha': '2031-11-24 00:00:00', 'rate': 0.05702088559440521}, {'fecha': '2031-12-24 00:00:00', 'rate': 0.05565135629790463}, {'fecha': '2032-01-24 00:00:00', 'rate': 0.05585668031279423}, {'fecha': '2032-02-24 00:00:00', 'rate': 0.057790435409961205}, {'fecha': '2032-03-24 00:00:00', 'rate': 0.06146797820474803}, {'fecha': '2032-04-24 00:00:00', 'rate': 0.06698024763570953}, {'fecha': '2032-05-24 00:00:00', 'rate': 0.07443072988764565}, {'fecha': '2032-06-24 00:00:00', 'rate': 0.08404236816293253}, {'fecha': '2032-07-24 00:00:00', 'rate': 0.09543783410635909}, {'fecha': '2032-08-24 00:00:00', 'rate': 0.10953762907938014}, {'fecha': '2032-09-24 00:00:00', 'rate': 0.12589590453000965}, {'fecha': '2032-10-24 00:00:00', 'rate': 0.14472675698100046}, {'fecha': '2032-11-24 00:00:00', 'rate': 0.1654687757938058}, {'fecha': '2032-12-24 00:00:00', 'rate': 0.18537930009054837}, {'fecha': '2033-01-24 00:00:00', 'rate': 0.2062709513251404}, {'fecha': '2033-02-24 00:00:00', 'rate': 0.2262882581692034}, {'fecha': '2033-03-24 00:00:00', 'rate': 0.2450627468737252}, {'fecha': '2033-04-24 00:00:00', 'rate': 0.2638670661486957}, {'fecha': '2033-05-24 00:00:00', 'rate': 0.2819263068958011}, {'fecha': '2033-06-24 00:00:00', 'rate': 0.2994374771469235}, {'fecha': '2033-07-24 00:00:00', 'rate': 0.31544236101457956}, {'fecha': '2033-08-24 00:00:00', 'rate': 0.330854571314503}]

2023-12-19 13:12:13,322:INFO - HTTP Request: DELETE https://tvpehjbqxpiswkqszwwv.supabase.co/rest/v1/ibr_implicita?fecha=not.is.null "HTTP/1.1 200 OK"
2023-12-19 13:12:13,516:INFO - HTTP Request: POST https://tvpehjbqxpiswkqszwwv.supabase.co/rest/v1/ibr_implicita "HTTP/1.1 201 Created"
2023-12-19 13:12:14,009:INFO - HTTP Request: POST https://tvpehjbqxpiswkqszwwv.supabase.co/auth/v1/token?grant_type=password "HTTP/1.1 200 OK"

In [2]:
from swap_functions.ibr_swap_ql_functions import ibr_swaps_quotes
from swap_functions.quotes_query import ibr_mean_query,ibr_mean_query_to_dictionary

In [3]:
ibr_data=pd.DataFrame(xty.get_date_range(table_name='ibr_swaps_cluster',date_column_name='execution_timestamp').data)

2023-12-19 13:12:21,620:INFO - HTTP Request: GET https://tvpehjbqxpiswkqszwwv.supabase.co/rest/v1/ibr_swaps_cluster?select=%2A "HTTP/1.1 200 OK"
/Users/avelezxerenity/Documents/GitHub/pysdk/src/xerenity/xty.py:134: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[column] = pd.to_datetime(df[column])
/Users/avelezxerenity/Documents/GitHub/pysdk/src/xerenity/xty.py:134: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[column] = pd.to_datetime(df[column])
/Users/avelezxerenity/Documents/GitHub/pysdk/src/xerenity/xty.py:134: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[column] = pd.to_datetime(df[column])
2023-12-19 13:12:22,325:INFO - HTTP Request: GET https://tvpehjbqxpiswkqszwwv.supabase.co/rest/v1/ibr_swaps_cluster?select=%2A "HTTP/1.1 200 OK"

In [4]:
ibr_data

,dissemination_identifier,action_type,event_timestamp,product_name,execution_timestamp,effective_date,expiration_date,notional_amount_leg_1,notional_amount_leg_2,notional_currency_leg_1,notional_currency_leg_2,fixed_rate_leg_1,fixed_rate_leg_2,underlier_id_leg_1,underlier_id_leg_2,floating_rate_reset_frequency_period_multiplier_leg_1,floating_rate_reset_frequency_period_multiplier_leg_2,days_diff_trade_effe,month_diff_effective_expiration,rate
0,828147739,NEWT,2023-12-12T13:57:44,InterestRate:IRSwap:OIS,2023-12-12T13:57:44,2024-03-20,2034-03-20,1.300000e+10,1.300000e+10,COP,COP,8.250,NaN,COP-IBR-OIS Compound,None,3.0,NaN,99,120,8.250
1,828147740,NEWT,2023-12-12T13:57:44,InterestRate:IRSwap:OIS,2023-12-12T13:57:44,2023-12-20,2033-12-20,1.330000e+10,1.330000e+10,COP,COP,8.000,NaN,COP-IBR-OIS Compound,None,3.0,NaN,8,120,8.000
2,828154631,NEWT,2023-12-12T14:10:27,InterestRate:IRSwap:OIS,2023-12-12T14:10:27,2023-12-14,2028-12-14,3.000000e+10,3.000000e+10,COP,COP,7.900,NaN,None,COP-IBR-OIS Compound,NaN,3.0,2,60,7.900
3,828156495,NEWT,2023-12-12T14:30:50,InterestRate:IRSwap:OIS,2023-12-12T14:30:50,2023-12-14,2028-12-14,4.400000e+10,4.400000e+10,COP,COP,NaN,7.895,COP-IBR-OIS-COMPOUND,None,3.0,NaN,2,60,7.895
4,828157468,NEWT,2023-12-12T14:33:05,InterestRate:IRSwap:OIS,2023-12-12T14:33:05,2023-12-14,2028-12-14,4.400000e+10,4.400000e+10,COP,COP,NaN,7.895,COP-IBR-OIS-COMPOUND,None,3.0,NaN,2,60,7.895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,560207138,NEWT,2023-02-28T20:04:40,InterestRate:IRSwap:OIS,2023-02-28T20:04:40,2023-03-02,2033-03-02,1.600000e+10,1.600000e+10,COP,COP,10.140,NaN,None,COP-IBR-OIS-COMPOUND,NaN,0.0,2,120,10.140
9496,560207499,NEWT,2023-02-28T20:04:40,InterestRate:IRSwap:OIS,2023-02-28T20:04:40,2023-03-02,2033-03-02,4.800000e+10,4.800000e+10,COP,COP,10.160,NaN,None,COP-IBR-OIS-COMPOUND,NaN,0.0,2,120,10.160
9497,560207938,NEWT,2023-02-28T20:06:47,InterestRate:IRSwap:OIS,2023-02-28T20:06:47,2023-03-02,2024-09-02,7.100000e+10,7.100000e+10,COP,COP,12.795,NaN,None,COP-IBR-OIS-COMPOUND,NaN,1.0,2,18,12.795
9498,560208134,NEWT,2023-02-28T20:06:59,InterestRate:IRSwap:OIS,2023-02-28T20:06:59,2023-03-02,2024-03-02,1.000000e+11,1.000000e+11,COP,COP,12.995,NaN,None,COP-IBR-OIS-COMPOUND,NaN,1.0,2,12,12.995
9499,560208996,NEWT,2023-02-28T20:09:47,InterestRate:IRSwap:OIS,2023-02-28T20:09:47,2023-03-02,2024-03-02,1.000000e+11,1.000000e+11,COP,COP,12.995,NaN,None,COP-IBR-OIS-COMPOUND,NaN,1.0,2,12,12.995

In [5]:
init_date=datetime(2023,12, 19).date()
final_date=init_date
start_date=datetime(2023, 12, 24).date()
day_to_avoid_fwd_ois=7
days_to_on=8

###Filtramos el Query por los parametros determinados. 
ibr_cluster_mean=ibr_mean_query(ibr_data,init_date,final_date,day_to_avoid_fwd_swaps=day_to_avoid_fwd_ois)
ibr_cluster_mean

                                     rate
month_diff_effective_expiration
3                                0.120650
6                                0.118650
9                                0.115075
12                               0.110300
24                               0.089721
36                               0.082217
48                               0.079100
60                               0.077023
96                               0.077650
108                              0.077650
120                              0.087992

In [ ]:
###creacion del directorio para llamarlos como una curva. Esta funcion devuelve in df. 
ibr_query=ibr_mean_query_to_dictionary(ibr_cluster_mean,'m')

## Llamados de las curvas y construccion de la fwd curve

In [ ]:
init_date=datetime(2023, 12, 16).date()
final_date=init_date
day_to_avoid_fwd_ois=7
days_to_on=8
curve=full_ibr_curve_creation(init_date,final_date,day_to_avoid_fwd_ois,days_to_on)
start_date=datetime(2024, 1, 15).date()
fwd_curve=fwd_rates_generation(curve,start_date,inverval_tenor=3,interval_period='m')

In [ ]:
fwd_curve

####ANALISIS historico con las series de tasas de creditos de vivienda

In [ ]:
#### Traer la historia del IBR swap. 
ibr_on=pd.DataFrame(xty.BanRep().get_econ_data_last_n(id_serie=15,n=15*365).data).drop('id_serie',axis=1)
ibr_on['fecha'] = pd.to_datetime(ibr_on['fecha'])
ibr_on.set_index('fecha', inplace=True)

cv_tasa=pd.read_csv('historic_non_vis.csv')
cv_tasa.set_index('fecha', inplace=True)

# Assuming df_tpm and df_cv_tasa are your DataFrames
ibr_on.index = pd.to_datetime(ibr_on.index)
cv_tasa.index = pd.to_datetime(cv_tasa.index)
# Resample TPM to daily and forward fill to fill missing values
df_tpm_resampled = ibr_on.resample('D').ffill()

# Merge CV_TASA with TPM using merge_asof
result_df = pd.merge_asof(cv_tasa, df_tpm_resampled, left_index=True, right_index=True, direction='nearest', suffixes=('tasa','valor'))

In [ ]:
import pandas as pd
import numpy as np


# Drop rows with NaN values
result_df = result_df.dropna(subset=['tasa','valor'])

# Perform linear regression with numpy
X = result_df['valor'].values
y = result_df['tasa'].values

# Add a column of ones for the constant term
X = np.column_stack((np.ones_like(X), X))

# Calculate the coefficients
beta = np.linalg.lstsq(X, y, rcond=None)[0]

# Plot the data and regression line
plt.scatter(result_df['valor'], result_df['tasa'], label='Data')
plt.plot(result_df['valor'], beta[0] + beta[1] * result_df['valor'], color='red', label='Linear Regression')

# Add labels and move legend to the lower right corner
plt.xlabel('IBR-on')
plt.ylabel('Credito vivienda')
plt.legend(loc='lower right')

# Display regression results in a box
plt.text(0.05, 0.9, f'Intercept: {beta[0]:.4f}\nSlope: {beta[1]:.4f}', transform=plt.gca().transAxes, bbox=dict(facecolor='white', alpha=0.8))

# Show the plot
plt.show()

def predict_valor_CV_TASA(ibr_on,slope,intercept):
    # Coefficients from the linear regression
    # intercept = 0.1234
    # slope = 0.5678

    # Use the formula to predict valor_CV_TASA
    predicted_valor_CV_TASA = intercept + slope * ibr_on

    return predicted_valor_CV_TASA

In [ ]:
import nbformat
fig = go.Figure()
fig.add_trace(go.Scatter(x=ibr_on['valor'].index, 
                         y=ibr_on['valor'],
                         mode='lines',
                         name='IBR-on historico e.a'))


fig.add_trace(go.Scatter(x=fwd_curve['rate'].index, 
                        y=nom_to_effective(fwd_curve['rate'],365)*100,
                        mode='lines',
                        name='IBR-on implicito e.a'))

fig.add_trace(go.Scatter(x=cv_tasa.index, 
                        y=cv_tasa['tasa'],
                        mode='lines',
                        name='Serie de creditos de vivienda no VIS -Banco de la republica '))
# Add traces for dates after today
fig.add_trace(go.Scatter(x=fwd_curve.index, 
                        y=predict_valor_CV_TASA(nom_to_effective(fwd_curve['rate'],365)*100,beta[1],beta[0]),
                        mode='lines',
                        name='Creditos de vivienda no VIS implicito e.a'))


# Update layout
fig.update_layout(
    title='Tasas IBR overnight y Creditos de vivienda no VIS ',
    xaxis=dict(title='Fechas'),
    yaxis=dict(title='Tasa e.a'),
)
# Show the plot
fig.show()
fig.write_html('/Users/avelezxerenity/Documents/GitHub/wpages/Ibr-on.html')

In [ ]:
ibr_on.to_csv('/Users/avelezxerenity/Documents/GitHub/wpages/ibr_ea_historica.csv', index=True)
fwd_curve.to_csv('/Users/avelezxerenity/Documents/GitHub/wpages/ibr_ea_implicita.csv', index=True)
cv_tasa.to_csv('/Users/avelezxerenity/Documents/GitHub/wpages/credito_vivienda_no_vis_ea_historica.csv', index=True)
predict_valor_CV_TASA(nom_to_effective(fwd_curve['rate'],365)*100,beta[1],beta[0]).to_csv('/Users/avelezxerenity/Documents/GitHub/wpages/credito_vivienda_no_vis_ea_implicita.csv', index=True)