In [2]:
import sys
sys.path.append("/Users/pjara/OneDrive/Documents/GitHub/xerenity-dm")
from dane_data_collector import DaneCollector
from data_collectors.fic_govt.fic import ficCollector
from data_collectors.fic_govt.trm import trmCollector

In [3]:
trm_col = trmCollector()

In [4]:
objeto_json = trm_col.get_raw_data()

https://www.datos.gov.co/resource/mcec-87by.json?$query=SELECT%20%60valor%60%20as%20__select_alias__%2C%20%60unidad%60%20as%20__select_alias1__%2C%20%60vigenciadesde%60%20as%20__select_alias2__%2C%20%60vigenciahasta%60%20as%20__select_alias3__%20ORDER%20BY%20%60vigenciahasta%60%20DESC%20LIMIT%20100

In [5]:
objeto_json.json()

[{'__select_alias__': '3943.03',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-22T00:00:00.000',
  '__select_alias3__': '2023-12-22T00:00:00.000'},
 {'__select_alias__': '3948.54',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-21T00:00:00.000',
  '__select_alias3__': '2023-12-21T00:00:00.000'},
 {'__select_alias__': '3925.77',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-20T00:00:00.000',
  '__select_alias3__': '2023-12-20T00:00:00.000'},
 {'__select_alias__': '3932.59',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-19T00:00:00.000',
  '__select_alias3__': '2023-12-19T00:00:00.000'},
 {'__select_alias__': '3956.76',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-16T00:00:00.000',
  '__select_alias3__': '2023-12-18T00:00:00.000'},
 {'__select_alias__': '3955.88',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-15T00:00:00.000',
  '__select_alias3__': '2023-12-15T00:00:00.000'},
 {'__select_alias__': '3999.43',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-14T00:00:00.000',
  '__select_alias3__': '2023-12-14T00:00:00.000'},
 {'__select_alias__': '3990.88',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-13T00:00:00.000',
  '__select_alias3__': '2023-12-13T00:00:00.000'},
 {'__select_alias__': '3982.5',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-12T00:00:00.000',
  '__select_alias3__': '2023-12-12T00:00:00.000'},
 {'__select_alias__': '3998.51',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-08T00:00:00.000',
  '__select_alias3__': '2023-12-11T00:00:00.000'},
 {'__select_alias__': '3989.55',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-07T00:00:00.000',
  '__select_alias3__': '2023-12-07T00:00:00.000'},
 {'__select_alias__': '4023.21',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-06T00:00:00.000',
  '__select_alias3__': '2023-12-06T00:00:00.000'},
 {'__select_alias__': '3999.91',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-05T00:00:00.000',
  '__select_alias3__': '2023-12-05T00:00:00.000'},
 {'__select_alias__': '3983.15',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-02T00:00:00.000',
  '__select_alias3__': '2023-12-04T00:00:00.000'},
 {'__select_alias__': '4045.22',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-12-01T00:00:00.000',
  '__select_alias3__': '2023-12-01T00:00:00.000'},
 {'__select_alias__': '3980.67',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-30T00:00:00.000',
  '__select_alias3__': '2023-11-30T00:00:00.000'},
 {'__select_alias__': '3957.77',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-29T00:00:00.000',
  '__select_alias3__': '2023-11-29T00:00:00.000'},
 {'__select_alias__': '3989.89',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-28T00:00:00.000',
  '__select_alias3__': '2023-11-28T00:00:00.000'},
 {'__select_alias__': '4044.51',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-25T00:00:00.000',
  '__select_alias3__': '2023-11-27T00:00:00.000'},
 {'__select_alias__': '4092.33',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-23T00:00:00.000',
  '__select_alias3__': '2023-11-24T00:00:00.000'},
 {'__select_alias__': '4060.15',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-22T00:00:00.000',
  '__select_alias3__': '2023-11-22T00:00:00.000'},
 {'__select_alias__': '4033.83',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-21T00:00:00.000',
  '__select_alias3__': '2023-11-21T00:00:00.000'},
 {'__select_alias__': '4116.59',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-18T00:00:00.000',
  '__select_alias3__': '2023-11-20T00:00:00.000'},
 {'__select_alias__': '4077.44',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-17T00:00:00.000',
  '__select_alias3__': '2023-11-17T00:00:00.000'},
 {'__select_alias__': '3976.84',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-16T00:00:00.000',
  '__select_alias3__': '2023-11-16T00:00:00.000'},
 {'__select_alias__': '3963.57',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-15T00:00:00.000',
  '__select_alias3__': '2023-11-15T00:00:00.000'},
 {'__select_alias__': '4037.19',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-11T00:00:00.000',
  '__select_alias3__': '2023-11-14T00:00:00.000'},
 {'__select_alias__': '4056.94',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-10T00:00:00.000',
  '__select_alias3__': '2023-11-10T00:00:00.000'},
 {'__select_alias__': '4065.79',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-09T00:00:00.000',
  '__select_alias3__': '2023-11-09T00:00:00.000'},
 {'__select_alias__': '4005.06',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-08T00:00:00.000',
  '__select_alias3__': '2023-11-08T00:00:00.000'},
 {'__select_alias__': '3975.09',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-04T00:00:00.000',
  '__select_alias3__': '2023-11-07T00:00:00.000'},
 {'__select_alias__': '4047.11',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-03T00:00:00.000',
  '__select_alias3__': '2023-11-03T00:00:00.000'},
 {'__select_alias__': '4117.71',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-02T00:00:00.000',
  '__select_alias3__': '2023-11-02T00:00:00.000'},
 {'__select_alias__': '4114.29',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-11-01T00:00:00.000',
  '__select_alias3__': '2023-11-01T00:00:00.000'},
 {'__select_alias__': '4060.83',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-31T00:00:00.000',
  '__select_alias3__': '2023-10-31T00:00:00.000'},
 {'__select_alias__': '4120.62',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-28T00:00:00.000',
  '__select_alias3__': '2023-10-30T00:00:00.000'},
 {'__select_alias__': '4154.94',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-27T00:00:00.000',
  '__select_alias3__': '2023-10-27T00:00:00.000'},
 {'__select_alias__': '4201.53',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-26T00:00:00.000',
  '__select_alias3__': '2023-10-26T00:00:00.000'},
 {'__select_alias__': '4213.97',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-25T00:00:00.000',
  '__select_alias3__': '2023-10-25T00:00:00.000'},
 {'__select_alias__': '4221.39',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-24T00:00:00.000',
  '__select_alias3__': '2023-10-24T00:00:00.000'},
 {'__select_alias__': '4238.85',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-21T00:00:00.000',
  '__select_alias3__': '2023-10-23T00:00:00.000'},
 {'__select_alias__': '4249.71',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-20T00:00:00.000',
  '__select_alias3__': '2023-10-20T00:00:00.000'},
 {'__select_alias__': '4227.39',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-19T00:00:00.000',
  '__select_alias3__': '2023-10-19T00:00:00.000'},
 {'__select_alias__': '4222.09',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-18T00:00:00.000',
  '__select_alias3__': '2023-10-18T00:00:00.000'},
 {'__select_alias__': '4249',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-14T00:00:00.000',
  '__select_alias3__': '2023-10-17T00:00:00.000'},
 {'__select_alias__': '4230.61',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-13T00:00:00.000',
  '__select_alias3__': '2023-10-13T00:00:00.000'},
 {'__select_alias__': '4212.5',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-12T00:00:00.000',
  '__select_alias3__': '2023-10-12T00:00:00.000'},
 {'__select_alias__': '4231.97',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-11T00:00:00.000',
  '__select_alias3__': '2023-10-11T00:00:00.000'},
 {'__select_alias__': '4386.66',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-07T00:00:00.000',
  '__select_alias3__': '2023-10-10T00:00:00.000'},
 {'__select_alias__': '4359.4',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-06T00:00:00.000',
  '__select_alias3__': '2023-10-06T00:00:00.000'},
 {'__select_alias__': '4252.09',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-05T00:00:00.000',
  '__select_alias3__': '2023-10-05T00:00:00.000'},
 {'__select_alias__': '4187.01',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-04T00:00:00.000',
  '__select_alias3__': '2023-10-04T00:00:00.000'},
 {'__select_alias__': '4141.43',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-10-03T00:00:00.000',
  '__select_alias3__': '2023-10-03T00:00:00.000'},
 {'__select_alias__': '4053.76',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-30T00:00:00.000',
  '__select_alias3__': '2023-10-02T00:00:00.000'},
 {'__select_alias__': '4085.57',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-29T00:00:00.000',
  '__select_alias3__': '2023-09-29T00:00:00.000'},
 {'__select_alias__': '4093.6',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-28T00:00:00.000',
  '__select_alias3__': '2023-09-28T00:00:00.000'},
 {'__select_alias__': '4068.73',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-27T00:00:00.000',
  '__select_alias3__': '2023-09-27T00:00:00.000'},
 {'__select_alias__': '4052.54',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-26T00:00:00.000',
  '__select_alias3__': '2023-09-26T00:00:00.000'},
 {'__select_alias__': '3948.7',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-23T00:00:00.000',
  '__select_alias3__': '2023-09-25T00:00:00.000'},
 {'__select_alias__': '3948.25',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-22T00:00:00.000',
  '__select_alias3__': '2023-09-22T00:00:00.000'},
 {'__select_alias__': '3907.21',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-21T00:00:00.000',
  '__select_alias3__': '2023-09-21T00:00:00.000'},
 {'__select_alias__': '3902.54',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-20T00:00:00.000',
  '__select_alias3__': '2023-09-20T00:00:00.000'},
 {'__select_alias__': '3905.95',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-19T00:00:00.000',
  '__select_alias3__': '2023-09-19T00:00:00.000'},
 {'__select_alias__': '3928.28',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-16T00:00:00.000',
  '__select_alias3__': '2023-09-18T00:00:00.000'},
 {'__select_alias__': '3926.59',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-15T00:00:00.000',
  '__select_alias3__': '2023-09-15T00:00:00.000'},
 {'__select_alias__': '3950.92',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-14T00:00:00.000',
  '__select_alias3__': '2023-09-14T00:00:00.000'},
 {'__select_alias__': '3993.53',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-13T00:00:00.000',
  '__select_alias3__': '2023-09-13T00:00:00.000'},
 {'__select_alias__': '3997.74',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-12T00:00:00.000',
  '__select_alias3__': '2023-09-12T00:00:00.000'},
 {'__select_alias__': '4012.26',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-09T00:00:00.000',
  '__select_alias3__': '2023-09-11T00:00:00.000'},
 {'__select_alias__': '4045.83',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-08T00:00:00.000',
  '__select_alias3__': '2023-09-08T00:00:00.000'},
 {'__select_alias__': '4093.04',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-07T00:00:00.000',
  '__select_alias3__': '2023-09-07T00:00:00.000'},
 {'__select_alias__': '4089.46',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-06T00:00:00.000',
  '__select_alias3__': '2023-09-06T00:00:00.000'},
 {'__select_alias__': '4063.36',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-02T00:00:00.000',
  '__select_alias3__': '2023-09-05T00:00:00.000'},
 {'__select_alias__': '4099.2',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-09-01T00:00:00.000',
  '__select_alias3__': '2023-09-01T00:00:00.000'},
 {'__select_alias__': '4085.33',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-31T00:00:00.000',
  '__select_alias3__': '2023-08-31T00:00:00.000'},
 {'__select_alias__': '4110.08',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-30T00:00:00.000',
  '__select_alias3__': '2023-08-30T00:00:00.000'},
 {'__select_alias__': '4111.52',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-29T00:00:00.000',
  '__select_alias3__': '2023-08-29T00:00:00.000'},
 {'__select_alias__': '4117.78',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-26T00:00:00.000',
  '__select_alias3__': '2023-08-28T00:00:00.000'},
 {'__select_alias__': '4076.9',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-25T00:00:00.000',
  '__select_alias3__': '2023-08-25T00:00:00.000'},
 {'__select_alias__': '4085.89',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-24T00:00:00.000',
  '__select_alias3__': '2023-08-24T00:00:00.000'},
 {'__select_alias__': '4120.07',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-23T00:00:00.000',
  '__select_alias3__': '2023-08-23T00:00:00.000'},
 {'__select_alias__': '4124.04',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-19T00:00:00.000',
  '__select_alias3__': '2023-08-22T00:00:00.000'},
 {'__select_alias__': '4093.96',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-18T00:00:00.000',
  '__select_alias3__': '2023-08-18T00:00:00.000'},
 {'__select_alias__': '4130.33',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-17T00:00:00.000',
  '__select_alias3__': '2023-08-17T00:00:00.000'},
 {'__select_alias__': '4096.08',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-16T00:00:00.000',
  '__select_alias3__': '2023-08-16T00:00:00.000'},
 {'__select_alias__': '4029.95',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-15T00:00:00.000',
  '__select_alias3__': '2023-08-15T00:00:00.000'},
 {'__select_alias__': '3973.41',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-12T00:00:00.000',
  '__select_alias3__': '2023-08-14T00:00:00.000'},
 {'__select_alias__': '3955.23',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-11T00:00:00.000',
  '__select_alias3__': '2023-08-11T00:00:00.000'},
 {'__select_alias__': '4031.65',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-10T00:00:00.000',
  '__select_alias3__': '2023-08-10T00:00:00.000'},
 {'__select_alias__': '4076.46',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-09T00:00:00.000',
  '__select_alias3__': '2023-08-09T00:00:00.000'},
 {'__select_alias__': '4077.9',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-05T00:00:00.000',
  '__select_alias3__': '2023-08-08T00:00:00.000'},
 {'__select_alias__': '4144.79',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-04T00:00:00.000',
  '__select_alias3__': '2023-08-04T00:00:00.000'},
 {'__select_alias__': '4056.99',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-03T00:00:00.000',
  '__select_alias3__': '2023-08-03T00:00:00.000'},
 {'__select_alias__': '4007.44',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-02T00:00:00.000',
  '__select_alias3__': '2023-08-02T00:00:00.000'},
 {'__select_alias__': '3898.48',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-08-01T00:00:00.000',
  '__select_alias3__': '2023-08-01T00:00:00.000'},
 {'__select_alias__': '3923.49',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-07-29T00:00:00.000',
  '__select_alias3__': '2023-07-31T00:00:00.000'},
 {'__select_alias__': '3932.04',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-07-28T00:00:00.000',
  '__select_alias3__': '2023-07-28T00:00:00.000'},
 {'__select_alias__': '3951.1',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-07-27T00:00:00.000',
  '__select_alias3__': '2023-07-27T00:00:00.000'},
 {'__select_alias__': '3978.83',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-07-26T00:00:00.000',
  '__select_alias3__': '2023-07-26T00:00:00.000'},
 {'__select_alias__': '3950.58',
  '__select_alias1__': 'COP',
  '__select_alias2__': '2023-07-25T00:00:00.000',
  '__select_alias3__': '2023-07-25T00:00:00.000'}]

In [6]:
df = trm_col.clean_raw_data_1(objeto_json)

In [8]:
df

      valor                    fecha
0   3943.03  2023-12-22T00:00:00.000
1   3948.54  2023-12-21T00:00:00.000
2   3925.77  2023-12-20T00:00:00.000
3   3932.59  2023-12-19T00:00:00.000
4   3956.76  2023-12-16T00:00:00.000
..      ...                      ...
95  3923.49  2023-07-29T00:00:00.000
96  3932.04  2023-07-28T00:00:00.000
97   3951.1  2023-07-27T00:00:00.000
98  3978.83  2023-07-26T00:00:00.000
99  3950.58  2023-07-25T00:00:00.000

[100 rows x 2 columns]

In [35]:
df.rename(columns = {"__select_alias__": "valor",
           "__select_alias2__": "fecha"}, inplace= True)

In [36]:
df.head()

     valor __select_alias1__                    fecha        __select_alias3__
0  3943.03               COP  2023-12-22T00:00:00.000  2023-12-22T00:00:00.000
1  3948.54               COP  2023-12-21T00:00:00.000  2023-12-21T00:00:00.000
2  3925.77               COP  2023-12-20T00:00:00.000  2023-12-20T00:00:00.000
3  3932.59               COP  2023-12-19T00:00:00.000  2023-12-19T00:00:00.000
4  3956.76               COP  2023-12-16T00:00:00.000  2023-12-18T00:00:00.000

In [38]:
df.drop(columns = ["__select_alias1__", "__select_alias3__"], axis=1, inplace=True)

In [39]:
df.head()

     valor                    fecha
0  3943.03  2023-12-22T00:00:00.000
1  3948.54  2023-12-21T00:00:00.000
2  3925.77  2023-12-20T00:00:00.000
3  3932.59  2023-12-19T00:00:00.000
4  3956.76  2023-12-16T00:00:00.000

In [41]:
type(df.fecha[1])

str